### ISSUE TITLE
Campsite and Reservation stores

### ISSUE THREAD

**Issue by ostrich93** [Camp-SAMI/campsight#15]
Create stores for the Campsite and Reservations. This is to enable the interaction between the icons displayed on map and list of campsite items with the queries: i.e their population will depend on the query contents.

**Comment by Ezugworie08** [comment]
Like we had discussed, when the HomePage component mounts, the CampSiteCollection components should be populated with a list of featured campsites and the Map component should plot their corresponding [Long, Lat] properties. 
With that said, won't it be better to have sub-stores per component requirement?
The CampsiteCollection and Map component could definitely use one sub-store. 
Please let us know what you think?
